[theme]
# Obliga a la app a iniciar SIEMPRE en modo claro
base="light"

# Colores institucionales aplicados desde la raíz
primaryColor="#FF5900"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8F9FA"
textColor="#1A1A1A"
